DETImotica/urls.py
from django.urls import include, path

urlpatterns = [
    path('gestao/', include('sensors.urls')),
]

handler404 = 'sensors.views.handler404'
handler500 = 'sensors.views.handler500'

sensors/urls.py
#URL config
from django.urls import path
from . import views

app_name = 'sensors'
urlpatterns = [
    path('', views.template, name='template'),
    path('rooms/', views.RoomsIndexView.as_view(), name='rooms'),
    path('sensors/', views.SensorsIndexView.as_view(), name='sensors'),
    path('types/', views.TypesIndexView.as_view(), name='types'),
    path('users/', views.UsersIndexView.as_view(), name='users'),
    path('notifications/', views.notifications, name='notifications'),
    path('abac/<slug:type>/<slug:id>', views.abac, name='abac'),
    path('sensors/<slug:room_id>/', views.SensorsIndexView.roomDetails, name="roomDetails"),

    path('login/', views.login, name='login'),
    path('api_login/', views.api_login, name='api_login'),
    path('logout/', views.logout, name='logout'),
    path('forbidden/', views.forbidden, name='forbidden'),

    path('get/key/<slug:uuid>/', views.key, name='api_key'),
    path('post/<slug:object>/<slug:id>', views.postObject, name='api_post'),
    path('delete/<slug:object>/<slug:id>', views.deleteObject, name='api_delete')
]

sensors/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    managed = False
    room_id = models.CharField(max_length=36)
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Sensor(models.Model):
    managed = False
    sensor_id = models.CharField(max_length=36)
    room_id = models.CharField(max_length=36)
    description = models.CharField(max_length=50)
    type = models.CharField(max_length=20)
    symbol = models.CharField(max_length=5)

    def __str__(self):
        return self.sensor_id

class Type(models.Model):
    managed = False
    type_id = models.IntegerField()
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    units = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class User(models.Model):
    managed = False
    user_id = models.CharField(max_length=36)
    email = models.CharField(max_length=50)
    admin = models.BooleanField()

    def __str__(self):
        return self.user_id

sensors/views.py
# from django.shortcuts import render

# Create your views here.
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
import requests, json
import asyncio, aiohttp
from DETImotica.settings import API_URL
import urllib.parse

from .models import Room, Sensor, Type, User

# Main views

class RoomsIndexView(generic.ListView):
    template_name = 'sensors/rooms.html'
    context_object_name = 'rooms_list'

    def get(self, *args, **kwargs):
        if 'allow' not in self.request.session:
            return redirect('sensors:login')
        if not self.request.session['allow']:
            return redirect('sensors:forbidden')

        try:
            return super(RoomsIndexView, self).get(*args, **kwargs)
        except ResponseException as r:
            if r.code == 401:
                return redirect('sensors:logout')
            else:
                raise Exception

    def get_context_data(self, **kwargs):
        ctx = super(RoomsIndexView, self).get_context_data(**kwargs)
        ctx['uname'] = self.request.session['uname']
        return ctx

    def get_queryset(self):
        return loadRooms(self)

def loadRooms(self):
    requestRoomsID = api_get_request('/rooms', self.request.session)
    if requestRoomsID.headers["Content-Type"]=="application/json":
        roomsList = []
        for (id, request) in get_async_loop().run_until_complete(api_get_bulk_async('/room', requestRoomsID.json()["ids"], self.request.session)):
            roomsList.append(Room(room_id=id,name=request['name'],description=request['description']))
        return roomsList
    return []

class SensorsIndexView(generic.ListView):
    template_name = 'sensors/sensors.html'
    context_object_name = 'rooms_list'

    def get(self, *args, **kwargs):
        if 'allow' not in self.request.session:
            return redirect('sensors:login')
        if not self.request.session['allow']:
            return redirect('sensors:forbidden')

        try:
            return super(SensorsIndexView, self).get(*args, **kwargs)
        except ResponseException as r:
            if r.code == 401:
                return redirect('sensors:logout')
            else:
                raise Exception

    def get_queryset(self):
        return loadRooms(self)

    def loadRoom(session, id):
        requestRoomsID = api_get_request('/rooms', session)
        if requestRoomsID.headers["Content-Type"]=="application/json":
            for room in requestRoomsID.json()["ids"]:
                if room==id:
                    request = api_get_request('/room/' + room, session).json()
                    return Room(room_id=room,name=request['name'],description=request['description'])
            return []
        return []

    def loadRoomSensors(session, room_id):
        requestSensorsID = api_get_request('/room/' + room_id + '/sensors', session)
        if requestSensorsID.headers["Content-Type"]=="application/json":
            sensorsList = []
            for (id, request) in get_async_loop().run_until_complete(api_get_bulk_async('/sensor', requestSensorsID.json()["ids"], session)):
                sensorsList.append(Sensor(sensor_id=id,room_id=request['room_id'],description=request['description'],type=request['data']['type'],symbol=request['data']['unit_symbol']))
            sensorsList.sort(key=lambda s: (s.type.lower(), s.symbol.lower(), s.description.lower() if s.description is not None else s.description))
            return sensorsList
        return []

    def deleteRoomSensors(request, room_id):
        requestSensorsID = api_get_request('/room/' + room_id + '/sensors', request.session)
        if requestSensorsID.headers["Content-Type"]=="application/json":
            get_async_loop().run_until_complete(api_delete_bulk_async('/sensor', requestSensorsID.json()["ids"], request.session))

    def roomDetails(request, room_id):
        if 'allow' not in request.session:
            return redirect('sensors:login')
        if not request.session['allow']:
            return redirect('sensors:forbidden')

        try:
            room = SensorsIndexView.loadRoom(request.session, room_id)
            if room != []:
                sensors = SensorsIndexView.loadRoomSensors(request.session, room_id)
                types = loadTypesInfo(request.session)
                return render(request, 'sensors/roomDetails.html', {'room': room, 'sensors': sensors, 'types': types, 'uname': request.session['uname']})
            raise Http404("Sala não existente")
        except ResponseException as r:
            if r.code == 401:
                return redirect('sensors:logout')
            else:
                raise Exception

class TypesIndexView(generic.ListView):
    template_name = 'sensors/types.html'
    context_object_name = 'types_list'

    def get(self, *args, **kwargs):
        if 'allow' not in self.request.session:
            return redirect('sensors:login')
        if not self.request.session['allow']:
            return redirect('sensors:forbidden')

        try:
            return super(TypesIndexView, self).get(*args, **kwargs)
        except ResponseException as r:
            if r.code == 401:
                return redirect('sensors:logout')
            else:
                raise Exception

    def get_context_data(self, **kwargs):
        ctx = super(TypesIndexView, self).get_context_data(**kwargs)
        ctx['uname'] = self.request.session['uname']
        return ctx

    def get_queryset(self):
        return loadTypesInfo(self.request.session)

def loadTypesInfo(session):
    requestTypes = api_get_request('/types', session)
    if requestTypes.headers["Content-Type"]=="application/json":
        typesList = []
        for (id, request) in get_async_loop().run_until_complete(api_get_bulk_async('/type', requestTypes.json()["ids"], session)):
            typesList.append(Type(type_id=id, name=request['name'],description=request['description'],units=", ".join(request['units'])))
        typesList.sort(key=lambda t: t.name)
        return typesList
    return []


class UsersIndexView(generic.ListView):
    template_name = 'sensors/users.html'
    context_object_name = 'users_list'

    def get(self, *args, **kwargs):
        if 'allow' not in self.request.session:
            return redirect('sensors:login')
        if not self.request.session['allow']:
            return redirect('sensors:forbidden')

        try:
            return super(UsersIndexView, self).get(*args, **kwargs)
        except ResponseException as r:
            if r.code == 401:
                return redirect('sensors:logout')
            else:
                raise Exception

    def get_context_data(self, **kwargs):
        ctx = super(UsersIndexView, self).get_context_data(**kwargs)
        ctx['uname'] = self.request.session['uname']
        return ctx

    def get_queryset(self):
        return loadUsers(self.request.session)

def loadUsers(session):
    requestUsers = api_get_request('/users/full', session)
    if requestUsers.headers["Content-Type"]=="application/json":
        usersList = []
        for user in requestUsers.json():
            usersList.append(User(user_id=user['id'], email=user['email'], admin=user['admin']))
        return usersList
    return []

def notifications(request):
    if 'allow' not in request.session:
        return redirect('sensors:login')
    if not request.session['allow']:
        return redirect('sensors:forbidden')
    return render(request, "sensors/notifications.html", {'uname': request.session['uname']})

class Policy:
    def __init__(self, subjects, actions, context, effect, description, uuid):
        self.subjects = ""
        self.actions = ', '.join(actions)
        self.context = ""
        self.effect = 'Allow' if effect == 'allow' else 'Deny'
        self.uuid = uuid
        self.description = description
        self.setSubjects(subjects)
        self.setContext(context)

    def setSubjects(self, subjects):
        res = []
        email = []
        for subject in subjects:
            subres = []
            for key in subject:
                if key == 'email':
                    email.append(subject[key])
                elif key == 'admin':
                    subres.append("Administradores")
                elif key == 'student':
                    subres.append("Estudantes")
                elif key == 'teacher':
                    subres.append("Docentes")
                elif 'courses' in key:
                    subres.append("Unidades Curriculares: " + ', '.join([str(x) for x in subject[key]]))
            if subres != []:
                res.append('- ' + ', '.join(subres))
        if email != []:
            res.append("- Email: " + ', '.join(email))
        self.subjects = '\n'.join(res)

    def setContext(self, context):
        res = []
        if context == {}:
            self.context = "Sempre"
        else:
            for key in context:
                if key == 'date':
                    res.append("- Dias: de " + context[key]['from'] + " a " + context[key]['to'])
                elif key == 'hour':
                    res.append("- Horas: de " + context[key]['from'] + " a " + context[key]['to'])
                elif key == 'ip':
                    res.append("- Rede: " + ('Interna' if context[key] == 'internal' else 'Externa'))
            self.context = '\n'.join(res)


def abac(request, type, id):
    if 'allow' not in request.session:
        return redirect('sensors:login')
    if not request.session['allow']:
        return redirect('sensors:forbidden')

    try:
        metadata = api_get_request('/' + type + '/' + id, request.session).json()
    except ResponseException:
        pass

    body = {
        'resources.'+type: id
    }
    data = api_get_request('/accessPolicies', request.session, data=body).json()

    policies = []
    for d in data:

sensors/templates/sensors/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

    <head>

      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">

      <title>{% block title %}{% endblock %} - DETImótica</title>

      <!-- Custom fonts for this template-->
      <link href="{% static "sensors/vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
      <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

      <link rel="shortcut icon" type="image/png" href="{% static 'sensors/images/favicon.png' %}"/>

      <!-- Custom styles for this template-->
      <link href="{% static "sensors/css/sb-admin-2.min.css" %}" rel="stylesheet">

      <style type="text/css">{% block custom-style %}{% endblock %}</style>

      <base href="/gestao/">

    </head>

    <body id="page-top">

      <!-- Page Wrapper -->
      <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

          <!-- Sidebar - Brand -->
          <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
            <div class="sidebar-brand-icon">
              <img style="display:table-cell;" src={% static "sensors/images/favicon.png" %} width="30" height="30" alt="DETImotica logo">
            </div>
            <div class="sidebar-brand-text mx-3">DETImótica</div>
          </a>

          <!-- Divider -->
          <hr class="sidebar-divider my-0">

          <!-- Nav Item - Dashboard -->
          <li class="nav-item" id="nav-home">
            <a class="nav-link" href="">
              <i class="fas fa-fw fa-link"></i>
              <span>Home</span></a>
          </li>

          <!-- Divider -->
          <hr class="sidebar-divider">

          <!-- Heading -->
          <div class="sidebar-heading">
            Inventário
          </div>

          <li class="nav-item" id="nav-rooms">
            <a class="nav-link" href="rooms">
              <i class="fas fa-fw fa-building"></i>
              <span>Salas</span></a>
          </li>

          <li class="nav-item" id="nav-sensors">
            <a class="nav-link" href="sensors">
              <i class="fas fa-fw fa-microchip"></i>
              <span>Sensores</span></a>
          </li>

          <li class="nav-item" id="nav-types">
            <a class="nav-link" href="types">
              <i class="fas fa-fw fa-thermometer-half"></i>
              <span>Tipos de Métricas</span></a>
          </li>

          <!-- Divider -->
          <hr class="sidebar-divider">

          <!-- Heading -->
          <div class="sidebar-heading">
            Acessos
          </div>


          <li class="nav-item" id="nav-users">
            <a class="nav-link" href="users">
              <i class="fas fa-fw fa-user"></i>
              <span>Utilizadores</span></a>
          </li>

          <!-- Divider -->
          <hr class="sidebar-divider">

          <!-- Heading -->
          <div class="sidebar-heading">
            App Mobile
          </div>


          <li class="nav-item" id="nav-notifications">
            <a class="nav-link" href="notifications">
              <i class="fas fa-fw fa-comment"></i>
              <span>Notificações</span></a>
          </li>

          <!-- Divider -->
          <hr class="sidebar-divider d-none d-md-block">

          <!-- Sidebar Toggler (Sidebar) -->
          <div class="text-center d-none d-md-inline">
            <button class="btn btn-link" id="sidebarToggle"></button>
          </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

          <!-- Main Content -->
          <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

              <!-- Sidebar Toggle (Topbar) -->
              <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
              </button>

                <h5 style="padding-left: 0.5em"><a style="color: #5a5c69" href=""><b>Plataforma de Gestão</b></a></h5>

              <!-- Topbar Navbar -->
              <ul class="navbar-nav ml-auto">

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="mr-2 d-none d-lg-inline text-gray-600 small"><b>{% block uname %}{% endblock %}</b></span>
                  </a>
                  <!-- Dropdown - User Information -->
                  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                      Logout
                    </a>
                  </div>
                </li>

              </ul>

            </nav>
            <!-- End of Topbar -->

            {% block content %}{% endblock %}

          </div>
          <!-- End of Main Content -->

            <div class="footer py-2 text-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="https://www.ua.pt/deti/"><img src="{% static "sensors/images/deti.png" %}" ></a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <hr>
                                <p class="mb-0"><a style="color: #5a5c69" href="https://detimotica.github.io/">Projeto em Engenharia Informática 2020 - Grupo 02 - MIECT</a></p>
                            </div>
                        </div>
                    </div>
                </div>
          <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

      </div>
      <!-- End of Page Wrapper -->

      <!-- Scroll to Top Button -->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>

      <!-- Logout Modal -->
      <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="logoutModalLabel">Confirmar Saída</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">Selecione o botão "Logout" para confirmar a saída da sessão.</div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
              <a class="btn btn-primary" href="logout">Logout</a>
            </div>
          </div>
        </div>
      </div>

      <!-- Error Modal -->
      <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="errorModalLabel">Falha na execução da operação</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
              <div class="modal-body"><p>Ocorreu um erro <b id="errorID"></b> na execução do seu pedido.</p><p>Lamentamos o sucedido. Por favor contacte a administração.</p></div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Fechar</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Notification Modal -->
      <div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="notificationModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="notificationModalLabel">Notificação enviada com sucesso</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body"><p>O anúncio chegará aos utilizadores brevemente.</p></div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Fechar</button>
            </div>
          </div>
        </div>
      </div>

      <!-- Bootstrap core JavaScript-->
      <script src="{% static "sensors/vendor/jquery/jquery.min.js" %}"></script>
      <script src="{% static "sensors/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

      <!-- Core plugin JavaScript-->
      <script src="{% static "sensors/vendor/jquery-easing/jquery.easing.min.js" %}"></script>

      <!-- Custom scripts for all pages-->
      <script src="{% static "sensors/js/sb-admin-2.min.js" %}"></script>

      {% block custom-script %}{% endblock %}

      <script>
          $.ajaxSetup({
            error: function(xhr, status, error) {
                if(xhr.status == 401) {
                    window.location.replace('login');
                }
                else {
                    $("#errorID").html(xhr.status + ' ' + error);
                    $("#errorModal").modal('show');
                }
            }
          });
          $("#nav-{% block nav-item %}{% endblock %}").addClass('active');
          $('#errorModal').on('hidden.bs.modal', function () {
                window.location.replace(window.location);
          });
          $('[data-toggle="tooltip"]').tooltip({
                trigger : 'hover'
          });
      </script>

    </body>
</html>

sensors/templates/sensors/forbidden.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login - DETImótica</title>

  <!-- Custom fonts for this template-->
  <link href="{% static "sensors/vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'sensors/images/favicon.png' %}"/>

  <!-- Custom styles for this template-->
  <link href="{% static "sensors/css/sb-admin-2.min.css" %}" rel="stylesheet">

  <base href="/gestao/">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background-image: url('{% static "sensors/images/deti_frente.jpg" %}')"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <img src="{% static 'sensors/images/logo.png' %}">
                    <br>
                    <h5 style="margin-top: 1em;" class="h5 text-gray-900 mb-4">Esta plataforma é destinada apenas a administradores</h5>
                    <h6 style="margin-top: 1em;" class="h6 text-gray-900 mb-4">Caso considere que devia ter acesso contacte a administração</h6>
                  </div>
                  <br><hr><br>
                  <a href="logout" class="btn btn-primary btn-user btn-block">
                    Voltar
                  </a>
                  <br><hr><br><br>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static "sensors/vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "sensors/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static "sensors/vendor/jquery-easing/jquery.easing.min.js" %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static "sensors/js/sb-admin-2.min.js" %}"></script>

</body>

</html>

sensors/templates/sensors/login.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login - DETImótica</title>

  <!-- Custom fonts for this template-->
  <link href="{% static "sensors/vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'sensors/images/favicon.png' %}"/>

  <!-- Custom styles for this template-->
  <link href="{% static "sensors/css/sb-admin-2.min.css" %}" rel="stylesheet">

  <base href="/gestao/">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background-image: url('{% static "sensors/images/deti_frente.jpg" %}')"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <img src="{% static 'sensors/images/logo.png' %}">
                    <br>
                    <h1 style="margin-top: 1em;" class="h4 text-gray-900 mb-4">Plataforma de Gestão</h1>
                  </div>
                  <br><hr><br>
                  <a href="api_login" class="btn btn-primary btn-user btn-block">
                    Login com o IdP
                  </a>
                  <br><hr><br><br>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static "sensors/vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "sensors/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static "sensors/vendor/jquery-easing/jquery.easing.min.js" %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static "sensors/js/sb-admin-2.min.js" %}"></script>

</body>

</html>

sensors/templates/sensors/sensors.html
{% extends 'sensors/base.html' %}
{% load static %}

{% block title %}Sensores{% endblock %}
{% block uname %}{{ uname }}{% endblock %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h2 mb-2 text-gray-800">Sensores</h1>
    <br>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DETI</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Sala</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for room in rooms_list %}
                    <tr>
                        <td>
                            <a href="{% url 'sensors:roomDetails' room_id=room.room_id  %}">{{ room }}</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if not rooms_list %}
            <p>Não existe nenhuma sala disponível.</p>
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

{% block nav-item %}sensors{% endblock %}